export enum ProfileInfoTypes {
    FETCH_PROFILE_INFO_REQUEST = "FETCH_PROFILE_INFO_REQUEST",
    FETCH_PROFILE_INFO_SUCCESS = "FETCH_PROFILE_INFO_SUCCESS",
    FETCH_PROFILE_INFO_FAILURE = "FETCH_PROFILE_INFO_FAILURE"
}